name: CI

on:
  schedule:
    - cron: "0 9 * * 1-5"  # Runs at 9:00 AM, Monday through Friday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Skip specified dates
        id: date-check
        run: |
          CURRENT_DATE=$(date +'%m-%d')
          if [[ "$CURRENT_DATE" == "11-01" || "$CURRENT_DATE" == "12-25" || "$CURRENT_DATE" =~ ^12-(2[6-9]|3[0-1])$ || "$CURRENT_DATE" == "01-01" ]]; then
            echo "Date is excluded, skipping job."
            exit 0
          fi

      - name: Install dependencies
        if: steps.date-check.outcome != 'success'  # Continue if not skipped
        run: npm install

      - name: Run Playwright Script
        if: steps.date-check.outcome != 'success'  # Continue if not skipped
        run: node ./run-playwright.sh

      - name: Upload screenshots
        if: always()  # Always run this step to capture screenshots even if the script fails
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: 'screenshots/*.png'   
