name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        if: steps.date-check.outcome != 'success'  # Continue if not skipped
        run: npm install

      - name: Run Playwright Script
        if: steps.date-check.outcome != 'success'  # Continue if not skipped
        run: node ./run-playwright.sh

      - name: Upload screenshots
        if: always()  # Always run this step to capture screenshots even if the script fails
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: './screenshots/*.png'   
